_BASE_: ../Base-bagtricks.yml

DATASETS:
  NAMES: ("Animals-HyenaID2022",)
  TESTS: ("Animals-HyenaID2022",)

OUTPUT_DIR: logs/Animals-HyenaID2022/bagtricks_R50

INPUT:
  SIZE_TRAIN: [ 384, 384 ]
  SIZE_TEST: [ 384, 384 ]

  REA:
    ENABLED: False
    PROB: 0.5

MODEL:
  BACKBONE:
    WITH_IBN: True